'use client';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,Volume2,VolumeX,Pause,Play,X} from 'lucide-react';
import type {Content,Project} from './content';
const safe=(s:string)=> /^(https?:\/\/|\/[^/]|media\/)/.test(s)?s:'';
function Media({p,detail=false}:{p:Project;detail?:boolean}){const ref=useRef<HTMLVideoElement>(null);const [error,setError]=useState(false);const [near,setNear]=useState(detail);useEffect(()=>{const el=ref.current;if(!el||detail)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting)setNear(true);},{rootMargin:"160px"});o.observe(el);return()=>o.disconnect();},[p.src,detail]);useEffect(()=>{setError(false);const el=ref.current;if(!el||detail)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const observer=new IntersectionObserver(([e])=>{if(e.isIntersecting&&!reduced)el.play().catch(()=>{});else el.pause();});observer.observe(el);return()=>observer.disconnect();},[p.src,detail,near]);return <>{p.type==='video'?<video ref={ref} src={near?safe(p.src):undefined} poster={safe(p.poster)} muted={!detail} loop playsInline controls={detail} preload={detail?"metadata":"none"} onError={()=>setError(true)}/>:<img src={safe(p.src)} alt={p.title} loading="lazy" onError={()=>setError(true)}/ >}{error&&<span className="media-error">媒体暂不可用，请替换地址或文件。</span>}</>}
export default function Portfolio({savedContent}:{savedContent:Content}){
 const [data,setData]=useState<Content>(savedContent),[draft,setDraft]=useState<Content>(savedContent),[filter,setFilter]=useState('All'),[sub,setSub]=useState('All'),[muted,setMuted]=useState(true),[playing,setPlaying]=useState(false),[status,setStatus]=useState(''),[loaded,setLoaded]=useState(!!savedContent),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Project|null>(null),[heroError,setHeroError]=useState(false);
 const hero=useRef<HTMLVideoElement>(null),editor=useRef<HTMLDialogElement>(null),detail=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){hero.current?.pause();setPlaying(false);}},[]);
 useEffect(()=>{const v=hero.current;if(!loaded||!v)return;const attempt=()=>{if(!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches)v.play().catch(()=>setPlaying(false));};attempt();document.addEventListener('visibilitychange',attempt);return()=>document.removeEventListener('visibilitychange',attempt);},[loaded,data.heroVideo]);
 const categories=Array.from(new Set(data.projects.filter(p=>filter==='All'||p.category===filter).map(p=>p.subcategory)));
 const projects=data.projects.filter(p=>(filter==='All'||p.category===filter)&&(sub==='All'||p.subcategory===sub));
 const navigate=(f:string)=>{setFilter(f);setSub('All');document.getElementById('works')?.scrollIntoView({behavior:'smooth'});};
 if(!loaded)return <main style={{minHeight:'100svh',background:'#050505',color:'#eee',display:'grid',placeItems:'center'}}><div role="status">{status?'内容暂时无法加载':'正在加载作品集…'}{status&&<button onClick={()=>location.reload()}>重新加载</button>}</div></main>;
 return <main>
 <section className="hero" id="home">
 <video ref={hero} className="hero-film" src={safe(data.heroVideo)} poster={safe(data.heroPoster)||undefined} preload="auto" autoPlay muted={muted} loop playsInline onError={()=>setHeroError(true)} onPlaying={()=>setPlaying(true)} onPause={()=>setPlaying(false)}/><div className="hero-shade"/>{!playing&&<button className="hero-start" onClick={()=>hero.current?.play().catch(()=>setHeroError(true))} aria-label="播放首页视频"><Play size={20}/>播放视频</button>}
 <header><a href="#home" className="brand">{data.brand}<sup>®</sup></a><nav aria-label="主要导航"><a href="#home">{data.navHome}</a><button onClick={()=>navigate('Videos')}>{data.navVideos}</button><button onClick={()=>navigate('Pictures')}>{data.navPictures}</button><a href="#contact">{data.navContact}<ArrowUpRight size={15}/></a></nav><span className="header-note">{data.studioNote}</span></header>
 <div className="hero-copy"><h1>{data.headline}</h1><div className="hero-intro"><span className="small-star">✳</span><p>{data.intro}</p></div></div>
 <div className="hero-bottom"><a href="#works" className="scroll-link"><span className="round"><ArrowDown size={19}/></span>{data.exploreLabel}</a><span className="reel-label">{data.reelLabel}</span><div className="video-tools"><button onClick={()=>{const v=hero.current;if(!v)return;if(v.paused)v.play().catch(()=>setHeroError(true));else v.pause();}} aria-label={playing?'暂停首页视频':'播放首页视频'}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button onClick={()=>setMuted(!muted)} aria-label={muted?'开启视频声音':'关闭视频声音'} aria-pressed={!muted}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}<span>Sound {muted?'off':'on'}</span></button></div></div>
 {heroError&&<p className="hero-error">视频暂不可用，可在编辑内容中替换。</p>}
 </section>
 <section className="works" id="works"><div className="section-heading"><h2>{data.workTitle}<sup>({data.projects.length.toString().padStart(2,'0')})</sup></h2><p>{data.workIntro}</p></div>
 <div className="filters"><div className="main-filters">{['All','Videos','Pictures'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>{setFilter(f);setSub('All');}}>{f==='All'?data.allLabel:f==='Videos'?data.navVideos:data.navPictures}<sup>{data.projects.filter(p=>f==='All'||p.category===f).length}</sup></button>)}</div><div className="sub-filters" aria-label="作品子类目"><button className={sub==='All'?'selected':''} onClick={()=>setSub('All')}>全部</button>{categories.map(c=><button key={c} className={sub===c?'selected':''} onClick={()=>setSub(c)}>{c}</button>)}</div></div>
 <div className="project-grid">{projects.map((p,i)=><article key={p.id} className={'project project-'+i}><button className="project-cover" onClick={()=>{setSelected(p);detail.current?.showModal();}} aria-label={'查看 '+p.title}><Media p={p}/><span className="cover-tag">{p.category==='Videos'?<Play size={12} fill="currentColor"/>:null}{p.category}</span><span className="open-project"><ArrowUpRight size={25}/></span></button><div className="project-caption"><h3>{p.title}</h3><span>{p.subcategory}<span className="year">{p.year}</span></span></div></article>)}</div>{!projects.length&&<p className="empty">这个分类还没有作品。</p>}
 <div className="work-foot"><span>{data.workFooter}</span><span>{projects.length} projects on view</span></div></section>
 <footer id="contact"><div className="contact-top"><p>{data.contactText}</p><a href={'mailto:'+data.email}>{data.talkLabel} <ArrowUpRight size={20}/></a></div><a className="contact-title" href={'mailto:'+data.email}>{data.contactTitle}<ArrowUpRight/></a><div className="footer-bottom"><a href={'mailto:'+data.email}>{data.email}</a><span>{data.copyright}</span><a href="#home">{data.topLabel}</a></div><p className="demo-note">{data.demoNote}</p></footer>
 {status&&!loaded&&<div className="load-warning" role="alert">{status}<button onClick={()=>location.reload()}>重新加载</button></div>}
 <dialog aria-label="项目详情" ref={detail} className="detail-dialog" onClose={()=>{detail.current?.querySelector('video')?.pause();setSelected(null);}}><button className="close-dialog" aria-label="关闭项目" onClick={()=>detail.current?.close()}><X/></button>{selected&&<><div className="detail-media"><Media p={selected} detail/></div><div className="detail-copy"><span>{selected.category} / {selected.subcategory} / {selected.year}</span><h2>{selected.title}</h2><p>{selected.description}</p></div></>}</dialog>
 </main>;
}
